package gelatin

import (
	"errors"
	"net/http"
)

type ApiKey interface {
	ToString() string
}

// AdminKey is an API key generated by authenticating
// as an admin user
type AdminKey ApiKey

func HttpStatusToErr(code int) error {
	switch code {
	case http.StatusOK, http.StatusNoContent:
		return nil
	default:
		return errors.New(http.StatusText(code))
	}
}
